<?php

namespace Devrun\CmsModule\Repositories;

use Kdyby\Doctrine\EntityRepository;

/**
 * ImageIdentifyEntityRepository
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ImageIdentifyRepository extends EntityRepository
{

}
