ALTER TABLE images ADD page_id INT DEFAULT NULL AFTER identify_id, ADD package_id INT DEFAULT NULL AFTER page_id;
ALTER TABLE images ADD CONSTRAINT FK_E01FBE6AC4663E4 FOREIGN KEY (page_id) REFERENCES page (id) ON DELETE CASCADE;
ALTER TABLE images ADD CONSTRAINT FK_E01FBE6AF44CABFF FOREIGN KEY (package_id) REFERENCES package (id) ON DELETE CASCADE;
CREATE INDEX IDX_E01FBE6AC4663E4 ON images (page_id);
CREATE INDEX IDX_E01FBE6AF44CABFF ON images (package_id);
ALTER TABLE package ADD base TINYINT(1) DEFAULT NULL AFTER module;
CREATE UNIQUE INDEX base_package_idx ON package (base, module);
